name: Windows RDP Direct

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP & Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user Administrator Password12345! /add
        net localgroup Administrators Administrator /add

    - name: Start Direct Tunnel
      run: |
        ssh -p 443 -o StrictHostKeyChecking=no -R 0:localhost:3389 a.pinggy.io
